-- ============================================================
-- DATA ANALYSER — Supabase Schema
-- Run this in Supabase Dashboard → SQL Editor
-- ============================================================


-- ============================================================
-- TABLES
-- ============================================================

-- Stores metadata for each uploaded CSV
CREATE TABLE datasets (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  filename     TEXT NOT NULL,
  row_count    INTEGER NOT NULL DEFAULT 0,
  columns      JSONB NOT NULL DEFAULT '[]',
  -- columns shape: [{ original_name, label, description, type }]
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Stores each CSV row as JSONB
CREATE TABLE dataset_rows (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  dataset_id   UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
  row_index    INTEGER NOT NULL,
  data         JSONB NOT NULL DEFAULT '{}'
  -- data shape: { col1: val1, col2: val2, ... } keyed by original_name
);

-- One chat session per conversation thread on a dataset
CREATE TABLE chat_sessions (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  dataset_id   UUID NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
  title        TEXT,
  -- auto-generated from first message via Gemini (nullable until first message sent)
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Individual messages within a session
CREATE TABLE chat_messages (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id   UUID NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
  role         TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content      TEXT NOT NULL,
  sql_query    TEXT,
  -- SQL generated by Gemini; stored for multi-turn context
  chart_config JSONB,
  -- shape: { type, title, x_key, y_keys, data[] }
  -- null for user messages and text-only assistant responses
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- User feedback (thumbs up/down) on assistant messages
CREATE TABLE message_feedback (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id   UUID NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rating       SMALLINT NOT NULL CHECK (rating IN (1, -1)),
  comment      TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (message_id, user_id)
  -- one feedback per user per message
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_datasets_user_id
  ON datasets (user_id);

CREATE INDEX idx_dataset_rows_dataset_id
  ON dataset_rows (dataset_id);

CREATE INDEX idx_dataset_rows_dataset_id_row_index
  ON dataset_rows (dataset_id, row_index);

CREATE INDEX idx_chat_sessions_user_id
  ON chat_sessions (user_id);

CREATE INDEX idx_chat_sessions_dataset_id
  ON chat_sessions (dataset_id);

CREATE INDEX idx_chat_messages_session_id
  ON chat_messages (session_id);

CREATE INDEX idx_chat_messages_session_id_created_at
  ON chat_messages (session_id, created_at);

CREATE INDEX idx_message_feedback_message_id
  ON message_feedback (message_id);


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE datasets        ENABLE ROW LEVEL SECURITY;
ALTER TABLE dataset_rows    ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_sessions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_messages   ENABLE ROW LEVEL SECURITY;
ALTER TABLE message_feedback ENABLE ROW LEVEL SECURITY;


-- datasets — full access to own rows only
CREATE POLICY "datasets: own rows" ON datasets
  FOR ALL USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- dataset_rows — access only via owned datasets
CREATE POLICY "dataset_rows: via owned dataset" ON dataset_rows
  FOR ALL USING (
    dataset_id IN (
      SELECT id FROM datasets WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    dataset_id IN (
      SELECT id FROM datasets WHERE user_id = auth.uid()
    )
  );

-- chat_sessions — full access to own sessions only
CREATE POLICY "chat_sessions: own rows" ON chat_sessions
  FOR ALL USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- chat_messages — access only via owned sessions
CREATE POLICY "chat_messages: via owned session" ON chat_messages
  FOR ALL USING (
    session_id IN (
      SELECT id FROM chat_sessions WHERE user_id = auth.uid()
    )
  )
  WITH CHECK (
    session_id IN (
      SELECT id FROM chat_sessions WHERE user_id = auth.uid()
    )
  );

-- message_feedback — full access to own feedback only
CREATE POLICY "message_feedback: own rows" ON message_feedback
  FOR ALL USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());
